from PyQt5.QtWidgets import QWidget, QGridLayout, QLabel, QHBoxLayout, QVBoxLayout, QFrame
from PyQt5.QtGui import QFont

def build_overview(self):
    from ui.graphs import MiniSparklineWidget

    widget = QWidget()
    layout = QGridLayout()
    layout.setSpacing(12)
    layout.setContentsMargins(6, 6, 6, 6)

    # Overview card grid: show compact cards with metric, value and mini graph
    # CPU
    self.cpu_label = QLabel("0%")
    self.cpu_label.setFont(QFont("Segoe UI", 14, QFont.Bold))
    self.cpu_trend = QLabel("")
    self.cpu_trend.setStyleSheet(f"color: {self.ui_accent}; font-weight: 700;")
    cpu_card, self.cpu_chart_view, self.cpu_series = self.create_chart("CPU", "#4CAF50", fixed_max=100, compact=True)
    cpu_top = QWidget()
    cpu_top_layout = QHBoxLayout(cpu_top)
    cpu_top_layout.setContentsMargins(0, 0, 0, 0)
    cpu_top_layout.addWidget(self.cpu_label)
    cpu_top_layout.addStretch()
    cpu_top_layout.addWidget(self.cpu_trend)
    cpu_card.layout().insertWidget(0, cpu_top)
    self.cpu_mini = MiniSparklineWidget("#4CAF50")
    cpu_card.layout().insertWidget(1, self.cpu_mini)
    cpu_card.setMaximumHeight(110)
    cpu_card.setMinimumWidth(260)
    layout.addWidget(cpu_card, 0, 0)

    # GPU
    self.gpu_label = QLabel("N/A")
    self.gpu_label.setFont(QFont("Segoe UI", 14, QFont.Bold))
    self.gpu_trend = QLabel("")
    self.gpu_trend.setStyleSheet(f"color: {self.ui_accent}; font-weight: 700;")
    gpu_card, self.gpu_chart_view, self.gpu_series = self.create_chart("GPU", "#9C27B0", fixed_max=100, compact=True)
    gpu_top = QWidget()
    gpu_top_layout = QHBoxLayout(gpu_top)
    gpu_top_layout.setContentsMargins(0, 0, 0, 0)
    gpu_top_layout.addWidget(self.gpu_label)
    gpu_top_layout.addStretch()
    gpu_top_layout.addWidget(self.gpu_trend)
    gpu_card.layout().insertWidget(0, gpu_top)
    self.gpu_mini = MiniSparklineWidget("#9C27B0")
    gpu_card.layout().insertWidget(1, self.gpu_mini)
    gpu_card.setMaximumHeight(110)
    gpu_card.setMinimumWidth(260)
    layout.addWidget(gpu_card, 0, 1)

    # RAM
    self.memory_label = QLabel("0%")
    self.memory_label.setFont(QFont("Segoe UI", 14, QFont.Bold))
    self.memory_trend = QLabel("")
    self.memory_trend.setStyleSheet(f"color: {self.ui_accent}; font-weight: 700;")
    ram_card, self.memory_chart_view, self.memory_series = self.create_chart("RAM", "#2196F3", fixed_max=100, compact=True)
    ram_top = QWidget()
    ram_top_layout = QHBoxLayout(ram_top)
    ram_top_layout.setContentsMargins(0, 0, 0, 0)
    ram_top_layout.addWidget(self.memory_label)
    ram_top_layout.addStretch()
    ram_top_layout.addWidget(self.memory_trend)
    ram_card.layout().insertWidget(0, ram_top)
    self.memory_mini = MiniSparklineWidget("#2196F3")
    ram_card.layout().insertWidget(1, self.memory_mini)
    ram_card.setMaximumHeight(110)
    ram_card.setMinimumWidth(260)
    layout.addWidget(ram_card, 0, 2)

    # Disk
    self.disk_label = QLabel("0%")
    self.disk_label.setFont(QFont("Segue UI", 14, QFont.Bold))
    self.disk_trend = QLabel("")
    self.disk_trend.setStyleSheet(f"color: {self.ui_accent}; font-weight: 700;")
    disk_card, self.disk_chart_view, self.disk_series = self.create_chart("Disk", "#FF9800", fixed_max=100, compact=True)
    disk_top = QWidget()
    disk_top_layout = QHBoxLayout(disk_top)
    disk_top_layout.setContentsMargins(0, 0, 0, 0)
    disk_top_layout.addWidget(self.disk_label)
    disk_top_layout.addStretch()
    disk_top_layout.addWidget(self.disk_trend)
    disk_card.layout().insertWidget(0, disk_top)
    self.disk_mini = MiniSparklineWidget("#FF9800")
    disk_card.layout().insertWidget(1, self.disk_mini)
    disk_card.setMaximumHeight(110)
    disk_card.setMinimumWidth(260)
    layout.addWidget(disk_card, 1, 0)

    # Network
    self.eth_label = QLabel("0%")
    self.eth_label.setFont(QFont("Segoe UI", 14, QFont.Bold))
    self.eth_trend = QLabel("")
    self.eth_trend.setStyleSheet(f"color: {self.ui_accent}; font-weight: 700;")
    eth_card, self.eth_chart_view, self.eth_series = self.create_chart("Network", "#00BCD4", fixed_max=100, compact=True)
    eth_top = QWidget()
    eth_top_layout = QHBoxLayout(eth_top)
    eth_top_layout.setContentsMargins(0, 0, 0, 0)
    eth_top_layout.addWidget(self.eth_label)
    eth_top_layout.addStretch()
    eth_top_layout.addWidget(self.eth_trend)
    eth_card.layout().insertWidget(0, eth_top)
    self.eth_mini = MiniSparklineWidget("#00BCD4")
    eth_card.layout().insertWidget(1, self.eth_mini)
    eth_card.setMaximumHeight(110)
    eth_card.setMinimumWidth(260)
    layout.addWidget(eth_card, 1, 1)

    # Processes small info card
    proc_card = QFrame()
    proc_card.setStyleSheet(f"QFrame {{ background-color: {self.ui_panel}; border-radius: 10px; padding: 12px; }}")
    proc_layout = QVBoxLayout(proc_card)
    proc_title = QLabel("Processes")
    proc_title.setStyleSheet(f"color: {self.ui_muted}; font-weight: 700;")
    proc_layout.addWidget(proc_title)
    self.process_label = QLabel("0")
    self.process_label.setFont(QFont("Segoe UI", 14, QFont.Bold))
    proc_layout.addWidget(self.process_label)
    proc_card.setMaximumHeight(110)
    proc_card.setMinimumWidth(260)
    layout.addWidget(proc_card, 1, 2)

    widget.setLayout(layout)
    return widget
